apiVersion: apps/v1
kind: Deployment
metadata:
  name: m365-agent
  labels:
    app: m365-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: m365-agent
  template:
    metadata:
      labels:
        app: m365-agent
    spec:
      containers:
      - name: m365-agent
        image: your-registry.azurecr.io/m365-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: m365-agent-secrets
              key: backend-url
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: m365-agent-secrets
              key: tenant-id
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: m365-agent-secrets
              key: client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: m365-agent-secrets
              key: client-secret
        - name: MICROSOFT_APP_ID
          valueFrom:
            secretKeyRef:
              name: m365-agent-secrets
              key: microsoft-app-id
        - name: MICROSOFT_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: m365-agent-secrets
              key: microsoft-app-password
        - name: AGENT_NAME
          value: "Structural Engineering Assistant"
        - name: AGENT_DESCRIPTION
          value: "AI-powered structural engineering document search and analysis assistant"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: m365-agent-service
spec:
  selector:
    app: m365-agent
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: m365-agent-secrets
type: Opaque
stringData:
  backend-url: "https://your-backend.azurewebsites.net"
  tenant-id: "your-tenant-id"
  client-id: "your-client-id"
  client-secret: "your-client-secret"
  microsoft-app-id: "your-microsoft-app-id"
  microsoft-app-password: "your-microsoft-app-password"